generic-service:
  nameOverride: hmpps-matomo-analytics
  productId: 'DPS035' # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  # the IRSA service account name for accessing AWS resources
  # serviceAccountName: "hmpps-template-typescript"

  replicaCount: 4

  image:
    repository: matomo
    tag: '5.5'
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-matomo-analytics-cert

  livenessProbe:
    httpGet:
      path: /matomo.php

  readinessProbe:
    httpGet:
      path: /matomo.php

  # Environment variables to load into the deployment
  env:
    MATOMO_DATABASE_ADAPTER: mysql
    MATOMO_DATABASE_TABLES_PREFIX: matomo_
    PHP_MEMORY_LIMIT: 2048M

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    matomo-rds:
      MATOMO_DATABASE_HOST: rds_instance_address
      MATOMO_DATABASE_DBNAME: database_name
      MATOMO_DATABASE_USERNAME: database_username
      MATOMO_DATABASE_PASSWORD: database_password

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-template-typescript
